### ISSUE TITLE
This is not an issue

### ISSUE THREAD

**Issue by SteveLobdell** [bphillips09/PFAdmin#5]
Brandon, can you tell me why your "Create container" works and mine doesn't?  I love this tool, but I prefer to be able to build the container on my own so I know what's going on.  I dont' see anything special in yours, I'm using a dockerfile to build mine that looks like this

FROM ubuntu
EXPOSE 30000:30000/udp
EXPOSE 443
RUN apt update
RUN apt-get -y install ca-certificates
RUN apt-get -y install nethogs

This doesn't work, but yours does.  Why?!?!?!

**Comment by bphillips09** [comment]
@SteveLobdell What steps are you using to build your container manually? Are you getting any error responses from the Docker daemon?
